/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class MockLockedGold extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    accountTotalLockedGold(arg0: string): TransactionObject<string>

    authorizedValidators(arg0: string): TransactionObject<string>

    authorizedBy(arg0: string): TransactionObject<string>

    nonvotingAccountBalance(arg0: string): TransactionObject<string>

    getAccountTotalLockedGold(account: string): TransactionObject<string>

    incrementNonvotingAccountBalance(
      account: string,
      value: number | string
    ): TransactionObject<void>

    decrementNonvotingAccountBalance(
      account: string,
      value: number | string
    ): TransactionObject<void>

    setAccountTotalLockedGold(account: string, value: number | string): TransactionObject<void>

    setTotalLockedGold(value: number | string): TransactionObject<void>

    getTotalLockedGold(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): MockLockedGold
}
