/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class MockValidators extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    isValidator(arg0: string): TransactionObject<boolean>

    meetsAccountLockedGoldRequirements(account: string): TransactionObject<boolean>

    getGroupNumMembers(group: string): TransactionObject<string>

    getAccountLockedGoldRequirement(account: string): TransactionObject<string>

    getTopGroupValidators(group: string, n: number | string): TransactionObject<string[]>

    getGroupsNumMembers(groups: string[]): TransactionObject<string[]>

    updateEcdsaPublicKey(
      arg0: string,
      arg1: string,
      arg2: (string | number[])[]
    ): TransactionObject<boolean>

    setValidator(account: string): TransactionObject<void>

    setDoesNotMeetAccountLockedGoldRequirements(account: string): TransactionObject<void>

    setNumRegisteredValidators(value: number | string): TransactionObject<void>

    setMembers(group: string, _members: string[]): TransactionObject<void>

    setAccountLockedGoldRequirement(
      account: string,
      value: number | string
    ): TransactionObject<void>

    getNumRegisteredValidators(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): MockValidators
}
