/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract'
import { TransactionObject, BlockType } from 'web3/eth/types'
import { Callback, EventLog } from 'web3/types'
import { EventEmitter } from 'events'
import { Provider } from 'web3/providers'

export class TestRandom extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions)
  _address: string
  options: contractOptions
  methods: {
    computeCommitment(randomness: string | number[]): TransactionObject<string>

    commitments(arg0: string): TransactionObject<string>

    getBlockRandomness(blockNumber: number | string): TransactionObject<string>

    getTestRandomness(blockNumber: number | string, cur: number | string): TransactionObject<string>

    renounceOwnership(): TransactionObject<void>

    revealAndCommit(
      randomness: string | number[],
      newCommitment: string | number[],
      proposer: string
    ): TransactionObject<void>

    setRandomnessBlockRetentionWindow(value: number | string): TransactionObject<void>

    transferOwnership(newOwner: string): TransactionObject<void>

    initialize(_randomnessBlockRetentionWindow: number | string): TransactionObject<void>

    addTestRandomness(
      blockNumber: number | string,
      randomness: string | number[]
    ): TransactionObject<void>

    initialized(): TransactionObject<boolean>
    random(): TransactionObject<string>
    owner(): TransactionObject<string>
    isOwner(): TransactionObject<boolean>
    randomnessBlockRetentionWindow(): TransactionObject<string>
  }
  deploy(options: { data: string; arguments: any[] }): TransactionObject<Contract>
  events: {
    RandomnessBlockRetentionWindowSet(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    OwnershipTransferred(
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ): EventEmitter

    allEvents: (
      options?: {
        filter?: object
        fromBlock?: BlockType
        topics?: (null | string)[]
      },
      cb?: Callback<EventLog>
    ) => EventEmitter
  }
  getPastEvents(
    event: string,
    options?: {
      filter?: object
      fromBlock?: BlockType
      toBlock?: BlockType
      topics?: (null | string)[]
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>
  setProvider(provider: Provider): void
  clone(): TestRandom
}
